### ISSUE TITLE
is there any way to match the inner part of string literals by using tressitter?

### ISSUE THREAD

**Issue by cursorzz** [RRethy/nvim-treesitter-textsubjects#1]
this is more something like `vi"` text object, but I would like the achieve that using treesitter, is it possible?

**Comment by RRethy** [comment]
Yes you can. Something like this should work:

```
; query for Lua parser
; it creates a capture @range
(((string) @str)
    (#offset! @str 0 1 0 -1 "range"))
```

However, why replace an existing text object, just using `vi"` is probably the best choice.

**Comment by RRethy** [comment]
I tried the query and it seems to not work, something like that should work though, maybe try asking in nvim-treesitter repo.

**Comment by cursorzz** [comment]
the reason is that I find this plugin act similiar to the plugin (wildfire.vim) that I am currently using, so I am trying to see if I can combine those two : )

**Comment by RRethy** [comment]
You can write a custom query to mimic the behaviour of wildfire.vim by using the `#offset!` query directive. You might also find `nvim-treesitter-incremental-selection` module useful from the `nvim-treesitter` repo.
