### ISSUE TITLE
Documentation for `#make-range`?

### ISSUE THREAD

**Issue by telemachus** [RRethy/nvim-treesitter-textsubjects#16]
I'm trying to define a capture that grabs a function in Go and (optionally) comments. I'm sorry to bug you with this, but is there fuller documentation somewhere for `#make-range`? I'm unsure where and how to place the `@start` and `@end` tokens. Thanks.

**Comment by RRethy** [comment]
AFAIK there's no documentation, I learned by reading the `nvim-treesitter` codebase and trying them out myself and seeing what the returned. You'll want to put the `start` and `end` on the first and last node you want the range to cover. This code may help show how it works:

https://github.com/RRethy/nvim-treesitter-textsubjects/blob/b18ab0e2fa677bc2f58062233ba5f7914a01e53f/lua/nvim-treesitter/textsubjects.lua#L111-L115

**Comment by telemachus** [comment]
Thanks so much.
