### ISSUE TITLE
Quantifiers `*` and `+`?

### ISSUE THREAD

**Issue by telemachus** [RRethy/nvim-treesitter-textsubjects#17]
I notice that you're using `+` and `*` in some of your queries (e.g., [here](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/master/queries/foam/textsubjects-smart.scm)).

Do those work for you? I ask because unless I'm confused treesitter (for textobjects?) doesn't yet support `*` and `+`. See, for example, [here](https://github.com/neovim/neovim/pull/15330) and [here](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/102).

I apologize if this question is out of place, but I'm struggling a bit to understand the treesitter implementation in neovim. Thanks.

**Comment by RRethy** [comment]
Those queries weren't written by me, I don't use the Foam programming language so they were submitted by a community member. I make use of `?` is a lot of my queries but from what I can tell the only place I use `+` is for the queries which match comments, https://github.com/RRethy/nvim-treesitter-textsubjects/blob/b18ab0e2fa677bc2f58062233ba5f7914a01e53f/queries/lua/textsubjects-smart.scm#L4-L9, and as you can see from the comment I left above the query, that query is broken (I guess I now know the reason).
