### ISSUE TITLE
BUG: Vanilla vim motion for repeating f/t operation etc... stops working in visual mode

### ISSUE THREAD

**Issue by shaun-mathew** [RRethy/nvim-treesitter-textsubjects#24]
Consider this piece of text:

http://www.test.com/asd/asd.

Let's say I want to visual select from http to the last slash.
I would go to the beginning of the line and press v to enter visual mode and then press f/.
This will highlight http:/. However, if I want to repeat this search while in visual mode, I have to press
; repeatedly to highlight to the /, but that operation does not work with this plugin (i.e. it doesn't
move the cursor forward and highlight the up to the next /)

**Comment by RRethy** [comment]
Then use a different keymap for nvim-treesitter-textsubjects config. This is configured in your own dotfiles, not in the plugin, the readme just offers a possible suggestion for a keymap which you have full control over configuring.
