### ISSUE TITLE
support textsubjects-smart-inner

### ISSUE THREAD

**Issue by Mr-LLLLL** [RRethy/nvim-treesitter-textsubjects#29]
if use textsubjects-smart, will be select $range, if support textsubjects-smart-inner like textsubjects-function-inner, maybe pretty goods. or use textsubjects-smart, don't skip inner, just extend to textsubjects-inner first, press again, to textsubjects

**Comment by RRethy** [comment]
You can create your own textsubjects to be used by the plugin. I'm not going to be adding more though at the moment.
