### ISSUE TITLE
`nvim-treesitter.ts_utils` deprecation warning

### ISSUE THREAD

**Issue by gennaro-tedesco** [RRethy/nvim-treesitter-textsubjects#33]
Thank you for the great plugin, it is awesome!

I am using the nightly version
```lua
NVIM v0.9.0-dev-935+g3a5dddf24-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```
and I see the treesitter deprecation warning
```
nvim-treesitter.ts_utils.is_in_node_range is deprecated: use vim.treesitter instead
```
probably in [this import](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/b913508f503527ff540f7fe2dcf1bf1d1f259887/lua/nvim-treesitter/textsubjects.lua#L3).

It may be useful to address it at some point :)

**Comment by RRethy** [comment]
This is a warning in the nvim-treesitter code base not nvim-treesitter-textsubjects. I use that import [here](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/b913508f503527ff540f7fe2dcf1bf1d1f259887/lua/nvim-treesitter/textsubjects.lua#L127) and [here](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/b913508f503527ff540f7fe2dcf1bf1d1f259887/lua/nvim-treesitter/textsubjects.lua#L189), both of which are calls to `update_selection` which is a non-deprecated function. On the latest version of `nvim-treesitter`, that function calls `vim.treesitter.get_node_range` [source](https://github.com/nvim-treesitter/nvim-treesitter/blob/2c2430d42f30d1aef8715aed933272c9a6898f4e/lua/nvim-treesitter/ts_utils.lua#L264). Are you on the latest nvim-treesitter?

**Comment by gennaro-tedesco** [comment]
> Are you on the latest nvim-treesitter?

I am on the [latest commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/2c2430d42f30d1aef8715aed933272c9a6898f4e). May it be that the deprecation is issued on import of the module `require('nvim-treesitter.ts_utils')` rather than on explicit call to its functions?

**Comment by RRethy** [comment]
> I am on the [latest commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/2c2430d42f30d1aef8715aed933272c9a6898f4e). May it be that the deprecation is issued on import of the module require('nvim-treesitter.ts_utils') rather than on explicit call to its functions?

Not according to the source code. Are you sure it's this plugin?

**Comment by RRethy** [comment]
You can try triggering an error to figure out where the function is being called from, `foobar.baz()` will give you a stack trace.

I'm going to close this issue since there's no indication it's this plugin causes the issue, if you can show a stack trace referencing this plugin's code which indicates an issue on my end then I'll reopen.

**Comment by gennaro-tedesco** [comment]
You are right. I did some deeper debugging and realised it is apparently `nvim-treesitter/nvim-treesitter-textobjects` that throws the exception (which initially I loaded on event with yours, generating confusion).

Apologies for having wasted some time :)

**Comment by RRethy** [comment]
no worries :)
