### ISSUE TITLE
Elegant fallback to incremental selection?

### ISSUE THREAD

**Issue by NReilingh** [RRethy/nvim-treesitter-textsubjects#35]
I love the ergonomics of treesitter's incremental selection by node, and textsubjects feels like a great drop-in enhancement for this. I like `\` and `<BS>` for initiating/incrementing and decrementing, so my config is something like this (not exactly lazy.nvim):

```lua
return {
  plugins = {
    {
      'RRethy/nvim-treesitter-textsubjects',
      event = { 'BufReadPost', 'BufNewFile' },
    }
  },
  ts_opts = {
    textsubjects = {
      enable = true,
      prev_selection = '<BS>',
      keymaps = {
          ['\\'] = 'textsubjects-smart',
      },
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = 'g\\',
        node_incremental = 'g\\',
        scope_incremental = false,
        node_decremental = 'g<BS>',
      },
    },
  },
  config = function()
    vim.keymap.set('n', '\\', 'V\\', { remap = true })
  end,
}
```

I'm using `g` prefixes to retain access to incremental_selection because I work in an assortment of languages, some of which have textsubjects support and some which do not. I would love to be able to have textsubjects fallback to treesitter's increment/decrement when textsubject support is not available.

Are there any ways that this could be done more elegantly? I could see defining keymaps which conditionally call either textsubjects or incremental_selection based on whether the current treesitter node is supported by textsubjects or not, but this seems like it would be fragile with nested languages and I don't know how to query textsubjects to determine which languages support `textsubjects-smart`. Ideally, I think textsubjects would transparently fallback to treesitter node increments and retain the `prev_selection` functionality throughout.

**Comment by RRethy** [comment]
This is not going to be implemented. Too much complexity for minimal return.
