### ISSUE TITLE
Julia TS node names have changed

### ISSUE THREAD

**Issue by ArbitRandomUser** [RRethy/nvim-treesitter-textsubjects#38]
I'm not sure why , but right now julia textsubjects is broken.
it looks like the node names are different , changing to appropriate node names in the queries scm seems to make it work.

`comment` is now `line_comment`
`array_expression` is now `vector_expression` , 

i dont have much of an idea on Treesitter, but i can make a PR with the changes that i did to get it working , may i ?

**Comment by RRethy** [comment]
Yea, feel free to make a PR and I'll merge. I'm not familiar with Julia so I personally won't be putting up a fix.

cc @timoleistner who originally added Julia support.

**Comment by timoleistner** [comment]
Since it's been a while and @ArbitRandomUser did not create a pull request, I've done it.
Sadly, I can't test this as I get the following error when I try to use smart textsubjects:
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at posit
ion 2 for language julia
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:201: in function 'prepare_query'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:397: in function 'iter_group_results'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:320: in function 'get_capture_matches'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:445: in function 'fn'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
        .../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:440: in function 'get_capture_matches_recursively'

        ...sitter-textsubjects/lua/nvim-treesitter/textsubjects.lua:111: in function 'select'
        [string ":lua"]:1: in main chunk
```

This does happen no matter where I do this in my code.

Please let me know if I should create a separate issue or if you need more information.

**Comment by RRethy** [comment]
> E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at posit
ion 2 for language julia

That would indicate your Julia parser may be out of date.

**Comment by timoleistner** [comment]
fixed it :)

**Comment by ArbitRandomUser** [comment]
was waiting for you to chime in @timoleistner, your fix is neat and more comprehensive than mine.
Thanks :)

**Comment by ArbitRandomUser** [comment]
bumping because i dont want to make a new issue for this , 
@timoleistner , could you also add in so that `let` blocks are also selected ?

**Comment by timoleistner** [comment]
Created a pull request for let statements.
btw, you can also find textsubjects by your own by using [TSPlayground](https://github.com/nvim-treesitter/playground).
I'd be happy if julia gets complete support by this plugin and I know there are some things probably still missing (like the `container-inner` file).

**Comment by ArbitRandomUser** [comment]
@timoleistner it seems the TS node names have been slightly modified again , 
`parameter_list` is no longer to be used , but im not sure what it should be replaced with ( `signature` ?) 

https://github.com/tree-sitter/tree-sitter-julia/issues/133
