### ISSUE TITLE
A text-subject mapping jupyter cell divider pattern: #%%

### ISSUE THREAD

**Issue by drusmanbashir** [RRethy/nvim-treesitter-textsubjects#39]
Hi I am newbie in lua and completely confused with text-objects. I hope you can help:

I use #%% inside my python files to quickly jump between code blocks. It also helps if i convert the .py file to .ipynb, in that it uses the #%% string to define cell boundaries in jupyter. Can you help create a tree-sitter text subject which recognises this pattern and a keymapping to help me jump from one occurence of #%% to next (and backwards)?

Thanks.

**Comment by RRethy** [comment]
I don't use python so that would have to be contributed from open source. You don't need to know Lua for this, just take a look at [other examples](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/master/queries/python/textsubjects-smart.scm).
