### ISSUE TITLE
no such mapping `nvim_buf_del_keymap` in `yaml` files

### ISSUE THREAD

**Issue by gennaro-tedesco** [RRethy/nvim-treesitter-textsubjects#42]
On neovim nightly, in particular
```
NVIM v0.10.0-dev-1496+g4c8fdc018-Homebrew
Build type: Release
LuaJIT 2.1.1699180677
```
I get the following exception while opening `.yaml` files (and `.yaml` files only, I haven't been able to reproduce it with any other file format, strangely enough)
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30: Error executing lua: ...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:31: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...sitter-textsubjects/lua/nvim-treesitter/textsubjects.lua:236: E31: No such mapping
stack traceback:
	[C]: in function 'nvim_buf_del_keymap'
	...sitter-textsubjects/lua/nvim-treesitter/textsubjects.lua:236: in function 'detach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:522: in function 'detach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:531: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:31: in function <...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30>
	[C]: in function 'nvim_buf_call'
	...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30: in function <...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_cmd'
	...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:31: in function <...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30>
	[C]: in function 'nvim_buf_call'
	...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30: in function <...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:30: in function <...llar/neovim/HEAD-4c8fdc0/share/nvim/runtime/filetype.lua:10>
```
which seems to point to [this line](https://github.com/RRethy/nvim-treesitter-textsubjects/blob/011c09784f1a95cf469a48c1993b664190440391/lua/nvim-treesitter/textsubjects.lua#L236C20-L236C20).

I find it strange that only yaml files are affected, so I thought the problem could lie within the yaml lsp configuration, however the error still persists even after removing said yaml configuration.

Do you think the error lies elsewhere? Perhaps you could point me to the right direction?

**Comment by RRethy** [comment]
Hey, sorry I forgot to respond to this. I'm pretty confused by this error, your best bet would be to create a minimal config to reproduce, I don't see how this plugin would be causing it.

**Comment by gennaro-tedesco** [comment]
Whilst trying to create a minimally reproducible example I have realised that this issue is caused by [vim-matchup](https://github.com/andymass/vim-matchup) when used in combination with this plugin; however, this plugin alone, as you point out, does not produce any error. The issue is probably on the side of the other plugin: I will do some more debugging but we can definitely close this one - apologies for the unnecessary ticket!
