### ISSUE TITLE
Undo support

### ISSUE THREAD

**Issue by kosayoda** [RRethy/nvim-treesitter-textsubjects#7]
Hello, thank you for the plugin. I have a feature idea in mind that I'm not sure the feasibility of.

Would it be possible to store previous selections so they can be undone via another keymap? Something like:

- opt-in
- stores X number of previous selections
- keybind to restore previous selection

Use case: Butterfingers and accidentally selecting one too far

**Comment by RRethy** [comment]
It's doable, I'm pretty busy right now though so I'm not sure when I'll get around to this though. I'll leave the issue open and link this issue for any work on it. If nothing's been merged for a month, try commenting again to remind me.
